### ISSUE TITLE
compilation failed: tocstyle.sty obsolete

### ISSUE THREAD

**Issue by doegox** [azonenberg/scopehal-docs#35]
When trying to compile the doc, I got an error about missing tocstyle.sty

Apparently tocstyle is an obsolete package, not provided anymore, which should be replaced.
https://tex.stackexchange.com/questions/565279/missing-tocstyle-sty-file suggests tocbasic.

**Comment by azonenberg** [comment]
Fixed in 15a9c03b1e8dbff355c7483dcae249db30223054 last week but I forgot to close the ticket until now. Oops.
